### ISSUE TITLE
web3.eth.filter INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1368]
cpp develop branch commit 7b6710a

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter says
web3.eth.filter(options)
options
fromBlock: The number of the earliest block (latest may be given to mean the most recent and pending currently mining, block).
toBlock: The number of the latest block (latest may be given to mean the most recent and pending currently mining, block).
address: An address or a list of addresses to restrict log entries by requiring them to be made from a particular account.
topics: An array of values which must each appear in the log entries.

Add this code to a dapp, using ethereum.js develop branch commit de5de9e:
```
web3.eth.filter({'fromBlock': 'latest'}).watch(function(res) {
  console.log(res)
});
```

cpp eth cli json rpc response is:
INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised

**Comment by gavofyork** [comment]
fixed in develop.

**Comment by ethers** [comment]
hmm I built cpp develop eth cli 0ff3080 and ethereum.js develop de5de9e (built it and copied to my dapp) and I am still seeing the issue using `web3.eth.filter({'fromBlock': 'latest'}).watch....`

`INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised` as soon as I load the dapp page...

(As documentation is still pending https://github.com/ethereum/ethereum.js/issues/136 I am not sure if I'm supposed to be making a different call now)

**Comment by ethers** [comment]
cpp develop e01002b

Here is an example of using `web3.eth.filter({'address': address, 'toBlock':'latest'}).watch` causing `web3.eth.filter INVALID_PARAMS`

https://github.com/ethers/ethereum.js/blob/eg1368/example/contract.html

To repro, save the file locally, open Chrome, and open using file:///pathToContract.html.  Also open the Chrome debugger JS console.
Then run Alethzero.  Back in Chrome click "create example contract".  Accept the AZ dialog, and then click Mine in AZ.  After contract has been mined, go back to Chrome and enter say "3" in the textbox.  You will then see the errors INVALID_PARAMS in the Chrome JS console.

**Comment by debris** [comment]
I will check this once again

**Comment by gavofyork** [comment]
Works fine under AZ with top reading:

```
	var web3 = parent.web3;
//    var web3 = require('ethereum.js');
//    web3.setProvider(new web3.providers.HttpProvider());
```

**Comment by ethers** [comment]
fixed on ethereum.js develop branch b78dffa
thanks @gavofyork and @debris
