### ISSUE TITLE
UPnP required to connect

### ISSUE THREAD

**Issue by caktux** [ethereum/cpp-ethereum#1404]
Before the last p2p/networking upgrades (a few weeks ago iirc), getting `UPnP device not found` could be ignored without any problem, which is a normal error message in docker containers since they default to bridge mode for networking, and mapping ports was sufficient. Using the same mappings (ie. external port 30303 to a container's port 30303) no longer is, and there's simply no connection being made. Even without mapping ports, connecting to any node with an opened port was enough. UPnP should remain optional as it was.

**Comment by subtly** [comment]
UPnP is optional and will remain optional. At the moment this scenario causes a segfault -- fixed in #1417.

**Comment by caktux** [comment]
I wasn't getting any segfault, and outgoing connections still fail unless a UPnP device is found.

**Comment by subtly** [comment]
segfault was fixed. Also try with: -L

**Comment by caktux** [comment]
I wasn't getting a segfault even before the segfault fix... but anyway, -L seems to work, however since it was working previously, at least part of the behavior allowed by -L should be the default.

**Comment by abrkn** [comment]
I'm unable to start `eth` without `--upnp off` in Ubuntu 14.04

**Comment by subtly** [comment]
Fixed in #1436. The -L option has been removed and there is now support for explicit --listen-ip and --public-ip options. If Listen IP is set, it will bind TCP and UDP to that IP. If listen ip is not set, and upnp is enabled, it'll try upnp. Otherwise it'll listen to all interfaces.

@abrkn This should be fixed now. Running with '-v 10' will show more logging if there is still an issue.
