### ISSUE TITLE
Hitting stack limit around 388624

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1995]
Start eth, wait a few blocks... eventually crashes with 'bus error 10'.
No further error messages. Build from source. Not trying to mine and not having passed any arguments to the command line. 

Aleth CTDs with http://pastebin.com/AAeADEuC

**Comment by subtly** [comment]
Windows is also hitting stack limit near block ~388624.

**Comment by subtly** [comment]
Note: Setting stack reserve to 67108864 fixes windows.

**Comment by stephantual** [comment]
FYI, build 63acdd37c94b3a7f1d4d4dd721eb04d0a7106d07 OSX, same problem:


```
▣┅▶  17:40:48|p2p|1293c7ff…|++eth/v0.9.23/Release/Linux/g++/int  OK - queued as unknown parent: #05fc3542…
▣┅▶  17:40:48|p2p|1293c7ff…|++eth/v0.9.23/Release/Linux/g++/int  Queuing block #6ce242a6… for import...
▣┅▶  17:40:48|p2p|1293c7ff…|++eth/v0.9.23/Release/Linux/g++/int  OK - ready for chain insertion.
▣┅▶  17:40:48|p2p|1293c7ff…|++eth/v0.9.23/Release/Linux/g++/int  Queuing block #af79f8c5… for import...
Bus error: 10
```

**Comment by gavofyork** [comment]
yes - well understood. we'll address it with an EVMFace/Executive refactor to make EVM calling flat.

**Comment by chfast** [comment]
Possible fix: #2116

**Comment by chfast** [comment]
Fixed by #2167.

**Comment by hmframos** [comment]
The "> Bus error: 10" bug is not solved. Installed yesterday eth in my Macbook. It took 20 minutes to crash with the above error.

Please find the logging messages and commands bellow:

eth -j --frontier -b -i

(++)Ethereum

Please enter your MASTER password: 
Ethereum (++) 1.1.4
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
Transaction Signer: XE820E0ZZQ1CVIY1B5UT58K0G2K6WV8XMS (d2fcc8bd-4e4d-b9f4-7c2f-b2257a8c8a3c - 0017b8aa)
Mining Beneficiary: XE820E0ZZQ1CVIY1B5UT58K0G2K6WV8XMS (d2fcc8bd-4e4d-b9f4-7c2f-b2257a8c8a3c - 0017b8aa)
Foundation: XE55PXQKKK4B9BYPBGT1XCYW6R5ELFAT6EM (00000000-0000-0000-0000-000000000000 - de0b2956)
  ℹ  09:00:21.596|p2p  UPnP device: http://192.168.1.254:8000/7ayaw1ky2f2/IGD/upnp/IGD.xml [st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 ]
Node ID: enode://cce564b19e8ca323ffcfbf4e067bcb36f0e55415dc98de74fd9d5721a89b709bd88588ee5688df34df400303e813636409cb15c2c75e14bdf12423a98030c0b9@0.0.0.0:0
JSONRPC Admin Session Key: MLOP9CyvLPA=
  ℹ  09:00:40.704|eth  SLOW IMPORT: #4de2547b…  # 1057214
  ℹ  09:00:40.704|eth    Import took: 0.566237
  ℹ  09:00:40.704|eth    preliminaryChecks: 0.002464
  ℹ  09:00:40.704|eth    enactment: 0.557809
  ℹ  09:00:40.704|eth    collation: 8e-06
  ℹ  09:00:40.705|eth    writing: 0.000749
  ℹ  09:00:40.705|eth    checkBest: 0.005064
  ℹ  09:00:40.705|eth    147  transactions
  ℹ  09:00:40.705|eth    3108511  gas used
  ℹ  09:01:41.384|eth  SLOW IMPORT: #15bc33f5…  # 1057219
  ℹ  09:01:41.385|eth    Import took: 0.598174
  ℹ  09:01:41.385|eth    preliminaryChecks: 0.015147
  ℹ  09:01:41.385|eth    enactment: 0.575825
  ℹ  09:01:41.385|eth    collation: 1.1e-05
  ℹ  09:01:41.385|eth    writing: 0.000828
  ℹ  09:01:41.385|eth    checkBest: 0.006253
  ℹ  09:01:41.385|eth    146  transactions
  ℹ  09:01:41.385|eth    3090732  gas used
> web3.eth.blockNumber
1057221
> web3.admin.eth.setMiningBenefactor(web3.eth.accounts[0])
true
> web3.admin.eth.setMining(true)
  ℹ  09:04:23.508|  Loading full DAG of seedhash: #1250db29…
> web3.admin.eth.setMining(true)true
> web3.admin.setVerbosity(6)
true
▣┅▶  09:06:43.614|p2p|7ca567f8…|Geth/v1.3.3/windows/go1.5.1  Already known in chain.
▣┅▶  09:06:43.622|p2p|016d1667…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:07:14.468|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:07:29.877|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:07:31.965|p2p|61e1ada9…|Parity/0.9.99/x86_64-gnu-linux  Already known in chain.
▣┅▶  09:08:03.975|p2p|de471bcc…|Geth/v1.3.3-c541b38f/linux/go1.5.1  Already known in chain.
▣┅▶  09:08:45.865|p2p|a979fb57…|Geth/v1.3.3-c541b38f/linux/go1.5.1  Already known in chain.
▣┅▶  09:08:46.441|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:09:30.607|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:09:52.479|p2p|3482b951…|Geth/v1.3.3-c541b38f/linux/go1.5.3  Already known in chain.
▣┅▶  09:10:00.689|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:10:06.482|p2p|61e1ada9…|Parity/0.9.99/x86_64-gnu-linux  Already known in chain.
▣┅▶  09:10:58.688|p2p|3482b951…|Geth/v1.3.3-c541b38f/linux/go1.5.3  Already known in chain.
▣┅▶  09:11:54.096|p2p|9bc5fc8e…|Geth/v1.3.3-c541b38f/linux/go1.6  Already known in chain.
▣┅▶  09:12:08.179|p2p|b6e0d834…|Geth/v1.3.2-54904379/linux/go1.4.2  Already known in chain.
▣┅▶  09:12:08.700|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:12:11.231|p2p|8ef63d6b…|Geth/v1.4.0-unstable/windows/go1.5.1  Already known in chain.
▣┅▶  09:12:39.076|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:14:36.653|p2p|61e1ada9…|Parity/0.9.99/x86_64-gnu-linux  Already known in chain.
▣┅▶  09:14:45.363|p2p|3482b951…|Geth/v1.3.3-c541b38f/linux/go1.5.3  Already known in chain.
▣┅▶  09:14:45.429|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:15:45.467|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:17:35.897|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:17:50.931|p2p|3482b951…|Geth/v1.3.3-c541b38f/linux/go1.5.3  Already known in chain.
▣┅▶  09:18:09.005|p2p|016d1667…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:18:09.091|p2p|77e6a595…|Geth/frontier-4.ether.camp/v1.3.2-54904379/linux/go1.4.2  Already known in chain.
▣┅▶  09:18:16.614|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:18:25.959|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:19:03.550|p2p|d20587cc…|Geth/v1.3.3/linux/go1.5.1  Already known in chain.
▣┅▶  09:19:03.573|p2p|de471bcc…|Geth/v1.3.3-c541b38f/linux/go1.5.1  Already known in chain.
> Bus error: 10

**Comment by chriseth** [comment]
This might  be fixed in version 1.2.0 which is to be released soon.
