### ISSUE TITLE
Chunking for NVIDIA cards

### ISSUE THREAD

**Issue by mooneyj** [ethereum/cpp-ethereum#2559]
Ubuntu15.04, Nvidia 660ti 2GB memory, but max memory allocation (geth gpuinfo)or(clinfo) is 500MB. 
Is it possible to mine with this card?
How can I split up the DAG?

john@alderhillone:~$ ethminer -G -F http://127.0.0.1:8545
[OPENCL]:Found suitable OpenCL device [GeForce GTX 660 Ti] with 2147155968 bytes of GPU memory
miner 23:35:04|ethminer Getting work package...

ℹ 23:35:09|ethminer Loading full DAG of seedhash: #290decd9…
miner 23:35:10|ethminer Getting work package...
miner 23:35:10|ethminer Grabbing DAG for #5a46dd85…
ℹ 23:35:14|ethminer Full DAG loaded
miner 23:35:21|ethminer Got work package:
miner 23:35:21|ethminer Header-hash: c21c407788fcbfac56d7157526e7a6455ec69e265ec74fe4d2d60f0803c1ac2c
miner 23:35:21|ethminer Seedhash: 5a46dd85298b0beff65ccf3006c4b5d2f7fa6ca8a5885a7f2132714fe7a48602
miner 23:35:21|ethminer Target: 000000002bf83e1cdec8746c78083e1637e163db9a5e141cd3a72a4c5c6c9216
miner 23:35:21|ethminer Mining on PoWhash #c21c4077… : 0 H/s = 0 hashes / 0.5 s
miner 23:35:21|ethminer Got work package:
miner 23:35:21|ethminer Header-hash: 36b08af8fcfc0c408110b59cd1102cfa781c5b2c26a80e1ee382f0f869e0acd3
miner 23:35:21|ethminer Seedhash: 5a46dd85298b0beff65ccf3006c4b5d2f7fa6ca8a5885a7f2132714fe7a48602
miner 23:35:21|ethminer Target: 000000002bf2bfc4ea19045deb590d852d521f098972df68b7edcaf4b110ccb4
miner 23:35:22|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 0.5 s
miner 23:35:22|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 1 s
miner 23:35:23|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 1.501 s
miner 23:35:23|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 2.002 s
miner 23:35:24|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 2.503 s
miner 23:35:24|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 3.004 s
miner 23:35:25|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 3.504 s

Output from geth gpuinfo:

=============================================
============ OpenCL Device Info =============
=============================================
Platform id 0
Platform Name NVIDIA CUDA
Platform Vendor NVIDIA Corporation
Platform Version OpenCL 1.1 CUDA 7.0.35
Platform Extensions cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts
Platform Profile FULL_PROFILE

Device OpenCL id 0
Device id for mining 0
Device Name GeForce GTX 660 Ti
Vendor NVIDIA Corporation
Version OpenCL 1.1 CUDA
Driver version 346.59
Address bits 32
Max clock freq 980
Global mem size 2147155968
Max constant buffer size 65536
Max mem alloc size 536788992
Max compute units 7
Max work group size 1024
Max work item sizes [1024 1024 64]
=============================================
Found 1 devices. Benchmark first GPU: geth gpubench 0
Mine using all GPUs: geth --minegpu 0
You may also need to enable chunking: --gpuchunks

**Comment by LefterisJP** [comment]
Issue should be fixed in latest develop branch. Reopen if that is not the case.

**Comment by mooneyj** [comment]
Still not working after pull and make. It now explicitly reports that it "Created one big buffer for the DAG". Is there an option to set cunk size for splitting the DAG?

```
john@alderhillone:~/ethereum/cpp-ethereum/build/ethminer$ ./ethminer -G -M
[OPENCL]:Found suitable OpenCL device [GeForce GTX 660 Ti] with 2147155968 bytes of GPU memory
Benchmarking on platform: GPU
Preparing DAG...
Warming up...
  ℹ  20:11:48|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  20:11:48|gpuminer0  Initialising miner...
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 660 Ti(OpenCL 1.1 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Created one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Creating buffer for header.
[OPENCL]:Mapping one big chunk.
[OPENCL]:clEnqueueWriteBuffer(-4)
[OPENCL]:clEnqueueWriteBuffer(-38)
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
```

**Comment by LefterisJP** [comment]
Hmm .. I see. This issue is different than what most people had. No you can't force chunking and you don't want to. Chunking is unstable and not proven to work correctly.


The telltale sign of your problem is:
```
[OPENCL]:clEnqueueWriteBuffer(-4)
[OPENCL]:clEnqueueWriteBuffer(-38)
```

That means you get a `CL_MEM_OBJECT_ALLOCATION_FAILURE` followed by a `CL_INVALID_MEM_OBJECT` failure in the same function. It could be due to your GPU indeed not being able to enqueue the DAG writting even though it did allocate one big buffer for it. 

This is strange. Our need for chunking or not is determined by the success or failure of the DAG allocation at the moment. I could make it more complicated and also include the enqueue command in the logic but I am not sure if it's a good idea. It needs a bit of thinking.

**Comment by LefterisJP** [comment]
Hello.

Would it be possible for you to test an ethminer built with this PR? https://github.com/ethereum/cpp-ethereum/pull/2575

If you can please try to see if your issue is addressed.

**Comment by mooneyj** [comment]
Thanks I hope this option works. Trying it now...

**Comment by mooneyj** [comment]
using git fetch origin refs/pull/2575/head:2575

Chunking is activated, but still;
```
[OPENCL]:clEnqueueMapBuffer(-4)
[OPENCL]:clEnqueueWriteBuffer(-38)
```
full output
```
john@alderhillone:~/ethereum/cpp-ethereum/build$ ./ethminer/ethminer -G -M
[OPENCL]:Found suitable OpenCL device [GeForce GTX 660 Ti] with 2147155968 bytes of GPU memory
Benchmarking on platform: GPU
Preparing DAG...
Warming up...
  ℹ  23:46:03|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  23:46:03|gpuminer0  Initialising miner...
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 660 Ti(OpenCL 1.1 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
[OPENCL]:Allocating/mapping single buffer failed with: clEnqueueWriteBuffer(-4)
[OPENCL]:Failed to allocate 1 big chunk. Max allocateable memory is 536788992. Trying to allocate 4 chunks.
[OPENCL]:Creating buffer for chunk 0
[OPENCL]:Creating buffer for chunk 1
[OPENCL]:Creating buffer for chunk 2
[OPENCL]:Creating buffer for chunk 3
[OPENCL]:Loading chunk kernels
[OPENCL]:Mapping chunk 0
[OPENCL]:Mapping chunk 1
[OPENCL]:clEnqueueMapBuffer(-4)
[OPENCL]:clEnqueueWriteBuffer(-38)
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0

```
