### ISSUE TITLE
Feature request: Getting triehash(receipts) block header via rpc

### ISSUE THREAD

**Issue by Phistr90** [ethereum/cpp-ethereum#2903]
Hi,

I figured out that with the current rpc call method eth_getBlockByNumber it is not possible to get all information needed for a block header.
There is no triehash(receipts).

For a project I need to get the block header of the pending block via rpc in order to validate the header hash later by a third party.

Would be nice if you could implement this feature.

Thanks Philipp

**Comment by gavofyork** [comment]
done.

**Comment by Phistr90** [comment]
still dont get the receiptsroot  in the eth_getBlockByNumber method
